#!/bin/bash
# update our bombsquad server

# just in case i miss anything-
set -e

SOURCE_PATH="src/bombsquad"

chk_pkg() {
    command -v "$1" &>/dev/null || {
        echo "Package '$1' not found. Install it via apt, snap, pacman..."
        exit 1
        }
}
# make sure we have the proper packages
chk_pkg curl
chk_pkg tar
chk_pkg git

confirm_update() {
    echo "WARNING: This will replace your current server at \"$SOURCE_PATH\" with the latest release."
    echo "Doing this is irreversible and will wipe any modifications you've made to the code, make sure to back up!"
    read -r -p "Do you want to continue? [y/n] " prc
    if [[ "$prc" == [yY] ]]
    then 
        echo ""
    else {
        echo "quitting..."
        exit 0
        }
    fi
}
# talk to the user about the dangers of file
# overwriting if they've (likely) already ran
# update, aka. already have a bombsquad folder
[[ -d "$SOURCE_PATH" ]] && confirm_update

# alright, we can make our paths now that we're sure
mkdir -p "$SOURCE_PATH"

TMP_DIR=$(mktemp -d)
# kill our tmp dir even on failure
trap 'rm -rf "$TMP_DIR"' EXIT

# download the latest bombsquad server linux x86-64 release
echo "Downloading latest 'BombSquad_Server_Linux_x86_64' release..."
echo "* asking \"https://ballistica.net\" for download links..."

CURLD=$(curl -s "https://ballistica.net/downloads")
DL_URL=$(echo "$CURLD" | grep -oP 'https://[^"]+BombSquad_Server_Linux_x86_64[^"]+\.tar\.gz' | head -1)
# make sure we actually scraped anything
[[ -z "$DL_URL" ]] && {
    echo "ERROR: couldn't scrape 'https://ballistica.net/downloads'."
    echo "check your internet connection?"
    exit 1
}

OUT_PATH="$TMP_DIR/bombsquad_server_linux.tar.gz"

echo "* fetching from \"$DL_URL\""
curl -L "$DL_URL" -o "$OUT_PATH" || {
    echo
    echo "ERROR: failure on archive download. check your internet connection?"
    exit 1
}

# extract and nicely locate our archive at our source
echo "Extracting archive at \"$OUT_PATH\" to \"$SOURCE_PATH\"..."
tar -xzf "$OUT_PATH" -C "$SOURCE_PATH" --strip-components=1 || {
    echo
    echo "ERROR: failure on archive extraction."
    echo "this shouldn't happen unless the archive is corrupted or incomplete."
    echo "try again. if this keeps happening:"
    echo " * check your internet connection"
    echo " * wait a couple of minutes before trying again"
    echo " * check if 'ballistica.net/downloads' is up and accessible"
    echo
    echo "if everything is fine but the script keeps failing, contact me!"
    echo
    exit 1
}
# finally, make the server file actually executable
chmod +x "$SOURCE_PATH/bombsquad_server"

# download fusecore too and apply it to our source server
echo "Downloading latest 'BombSquad: FuseCore' release..."

OUT_PATH="$TMP_DIR/dist"
git clone "https://github.com/NST-Servers/fusecore/" "$OUT_PATH"
cp -fr "$OUT_PATH" "$SOURCE_PATH"

echo "Deleting irrelevant project files"
rm -rf "$SOURCE_PATH/dist/.git/"
rm -rf "$SOURCE_PATH/dist/.vscode/"
rm -f "$SOURCE_PATH/dist/.gitignore"
rm -f "$SOURCE_PATH/dist/.pylintrc"
rm -f "$SOURCE_PATH/dist/black-formatting"
rm -f "$SOURCE_PATH/dist/update"

# patch bascenev1lib to load fusecore
chmod +w "src/bombsquad/dist/ba_data/python/bascenev1lib/__init__.py"
echo import fusecore >> "src/bombsquad/dist/ba_data/python/bascenev1lib/__init__.py"

# hooray! we've done it!
echo "Server update completed!"
echo 
